---
# tasks file for egeneralov.disable_ipv6

- name: "sysctl : net.ipv6.conf.all.disable_ipv6"
  sysctl:
    name: net.ipv6.conf.all.disable_ipv6
    value: 1
    sysctl_set: yes
    state: present
    reload: yes

- name: "sysctl : net.ipv6.conf.default.disable_ipv6"
  sysctl:
    name: net.ipv6.conf.default.disable_ipv6
    value: 1
    sysctl_set: yes
    state: present
    reload: yes
